Repository LoginRadius/ps-softlist, pull requests merged in 2020-10, with the labels that each got.

#5 Add something.
  Contributing.md
  README.md
  WhiteListSoftware.csv
Labels: in review

#8 Add email template feature
  ScanInstalledSoftwars.ps1
Labels: Ready for Merge, in review

#9 Added Parameters for SMTP host and Port
  ScanInstalledSoftwars.ps1
Labels: hacktoberfest

#10 added choice option for the SMTP Provider
  ScanInstalledSoftwars.ps1
Labels: hacktoberfest
